### ISSUE TITLE
Can't open file

### ISSUE THREAD

**Issue by zerogetsamgow** [HughParsonage/ASGS#1]
Hi Hugh

I am a github novice. So, please excuse my ignorance. I was hoping to download this file, but received the following error message. 

`Attempting install of ASGS (700 MB) from Dropbox. This should take some minutes to download.`
`trying URL 'https://dl.dropbox.com/s/zmggqb1wmmv7mqe/ASGS_0.4.0.tar.gz'`
`Error in download.file(url = "https://dl.dropbox.com/s/zmggqb1wmmv7mqe/ASGS_0.4.0.tar.gz",  : `
      `cannot open URL 'https://dl.dropbox.com/s/zmggqb1wmmv7mqe/ASGS_0.4.0.tar.gz'`
`In addition: Warning message:`
`In download.file(url = "https://dl.dropbox.com/s/zmggqb1wmmv7mqe/ASGS_0.4.0.tar.gz",  :` `InternetOpenUrl failed: 'The date in the certificate is invalid or has expired'`

I thought I would mention this since you asked people to comment if they had problems.

**Comment by HughParsonage** [comment]
Hi, 

Yes this is exactly the sort of thing I'd like to know about. Thanks for filing.

Unfortunately (or not), I can't reproduce this issue, either on my machine or on a remote machine. It's possible you got unlucky and the Dropbox certificate was out-of-date for a few minutes during which you encountered the error. Could you try again?

**Comment by zerogetsamgow** [comment]
Thanks Hugh

No luck on a second attempt. I will try again from home tonight. It might be Treasury's security settings are preventing me from opening the URL.

**Comment by HughParsonage** [comment]
Ah that does sound like the problem. Let me know if there's another way of distributing the tarball that Treasury will accept.

**Comment by zerogetsamgow** [comment]
Seems to be working fine from my home computer.
