### ISSUE TITLE
R 3.5

### ISSUE THREAD

**Issue by DNC1971** [HughParsonage/ASGS#2]
Hi,

I am getting the following message when trying to install this package. 

install.packages("ASGS")
Installing package into ‘C:/Users/dcresp/Documents/R/win-library/3.5’
(as ‘lib’ is unspecified)
Warning in install.packages :
  package ‘ASGS’ is not available (for R version 3.5.0)

**Comment by HughParsonage** [comment]
Hello, `ASGS` is not on CRAN: it's about 1 GB and CRAN's limit is 5 MB. The preferred way to install it is to use `ASGS.foyer`

```r
install.packages("ASGS.foyer")
library(ASGS.foyer)
install_ASGS()
```

Please reopen if the above doesn't work.
