### ISSUE TITLE
Unable to download ASGS_0.4.0.tar.gz

### ISSUE THREAD

**Issue by MikeTheSnowman** [HughParsonage/ASGS#4]
When trying to install this R package, the install fails because it's not able to access the "ASGS_0.4.0.tar.gz" file from dropbox. The URL that fails is:
https://dl.dropbox.com/s/zmggqb1wmmv7mqe/ASGS_0.4.0.tar.gz

When manually navigating to this page, you're presented with a 403 error.

**Comment by jane-jianfangzhang** [comment]
I got this issue since 27/10/2020, I emailed dropbox and got replied:"Dropbox shared link via 'dl.dropbox.com' is not officially supported". Hopefully this issue can be fixed soon

**Comment by HughParsonage** [comment]
Sorry for the delay and thank you for the report! I'll upload a new version of `ASGS.foyer` to CRAN soon, but for now:

```r
remotes::install_github("HughParsonage/ASGS.foyer")
library(ASGS.foyer)
install_ASGS()
```

should work.
